app/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from .views import Producto, Cliente
from django.contrib.auth.views import LoginView,LogoutView

#---------- rutas de la API ----------------------------
urlpatterns = [
    path('api/', views.API_objects.as_view()),
    path('api/<int:pk>/', views.API_objects_details.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

#---------- rutas de la app ----------------------------
urlpatterns += [   
    path('', views.index),
    path('quienes', views.quienes),
    path('nba', views.nba),
    path('finalFantasy', views.finalFantasy),
    path('blairWitch', views.blairWitch),
    path('ingresarProducto', views.ingresarProducto),
    path('ingresarCliente', views.ingresarCliente),
    path('listarProductosFull', views.listarProductosFull),
    path('listarClientesFull', views.listarClientesFull),
    path('editarProducto/<int:producto_id>', views.editarProducto),
    path('editarCliente/<int:cliente_id>', views.editarCliente),
    path('borrarProducto/<int:producto_id>', views.borrarProducto),
    path('borrarCliente/<int:cliente_id>', views.borrarCliente),
    path('listarProductos', views.listarProductos),
     path('listarClientes', views.listarClientes),
    path('inicio', views.inicio),
    
]

#---------- login ----------------------------
urlpatterns+= [
     
    #path('',views.indexView,name='home'),
    #path('dashboard/',views.dashboardView,name='dashboard'),
    path('login/',LoginView.as_view(),name='login_url'),
    path('register/',views.registerView,name='register_url'),
    path('logout/',LogoutView.as_view(),name='logout_url'),
]

appCrud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
  	  	path('admin/', admin.site.urls),
        path('', include('app.urls')),
        path('ingresarProducto', include('app.urls')),
        path('ingresarCliente', include('app.urls')),
        path('listarProductosFull', include('app.urls')),
        path('listarClientesFull', include('app.urls')),
        path('editarProducto/<int:producto_id>', include('app.urls')),
        path('editarCliente/<int:cliente_id>', include('app.urls')),
        path('borrarProducto/<int:producto_id>', include('app.urls')),
        path('borrarCliente/<int:cliente_id>', include('app.urls')),
        path('listarProductos', include('app.urls')),
        path('listarClientes', include('app.urls')),
        
       
        
        
        
      

]

app/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _

# Create your models here.


class Producto(models.Model):
    nombre = models.CharField(max_length=20)
    descripcion = models.TextField(null=True)
    clasificacion = models.CharField(max_length=30)
    precio= models.IntegerField()

    def __str__(self):
        return self.nombre


class Cliente(models.Model):
    producto = models.ForeignKey(
    Producto, null=True, blank=True, on_delete=models.CASCADE)
    rut = models.CharField(max_length=15)
    nombre = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=30)
    apellido_materno = models.CharField(max_length=30)
    telefono = models.CharField(max_length=20)
    domicilio = models.CharField(max_length=50)
    region = models.CharField(max_length=50, blank=True, null=True)
    comuna = models.CharField(max_length=50, blank=True, null=True)
    fecha_registro = models.DateTimeField(auto_now=True)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return self.nombre
    

app/templates/app/Mis Perris - Registro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Mis Perris - Registro</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

       <!-- Estilos -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/estilos.css' %}">

        <!-- Scripts -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/script.js' %}"></script>
        <script src="{% static 'js/jquery.validate.min.js' %}"></script>             
        <script src="{% static 'js/cargarData.js' %}"></script>
        <script defer src="{% static 'js/reglas.js' %}"></script>        
    </head>

    <body class="content">

        <!-- Cabezera -->
         <nav id="navbar">
            <div id="navbar-logo">            
                <img src="{% static 'img/img/logo.png' %}" alt="logo">
            </div>
            <div id="nav">
                <ul>
                    <li class="nav-item"><a href="{% url 'index_MisPerris' %}">inicio</a></li>
                    <li class="nav-item"><a href="#">servicios</a></li>
                    <li class="nav-item"><a href="#">quienes somos</a></li>
                    <li class="nav-item"><a href="#">contáctanos</a></li>
                    <li class="nav-item"><a href="{% url 'carrera_crear' %}">registrarse</a></li>
                </ul>
            </div>                                 
        </nav>

        <!-- Infrmacion de contacto -->
        <div id="contact">
            <div id="p1">+ 56 9 98765431</div>
            <div id="p2">Rescate y adopción de perros callejeros</div>
            <div id="p3">
                <ul>
                    <li><div class="social"><img height="16" src="{% static 'img/icons/facebook-f-brands.svg' %}" alt="facebook"></div></li>
                    <li><div class="social"><img height="16" src="{% static 'img/icons/google-plus-g-brands.svg' %}" alt="google"></div></li>
                    <li><div class="social"><img height="16" src="{% static 'img/icons/instagram-brands.svg' %}" alt="instagram"></div></li>
                    <li><div class="social"><img height="16" src="{% static 'img/icons/envelope-solid.svg' %}" alt="email"></div></li>                    
                </ul>
            </div>
        </div>

        <!-- Formulario -->
        <div id="registro" class="container">

            <h1 class="display">Registro</h1><br>

            <form action="envio.html" method="POST" id="formulario" >

                <div class="form-group">
                    <label>Correo Electronico</label><br>
                    <input type="email" name="txtCorreoElectronico" value="" required="" class="form-control"
                           placeholder="Ingrese Email"/>
                </div>

                <div class="form-group">                    
                    <label>RUN</label><br>
                    <input type="text" name="txtRun" id="id_run" required oninput="" value="" class="form-control"
                           placeholder="Ingrese RUN"/>
                    <small id="emailHelp" class="text-muted">Ejemplo: 19243465-3</small>
                </div>

                <div class="form-group">
                    <label>Nombre Completo</label><br>
                    <input type="text" name="txtNombreCompleto" value="" required="" class="form-control"
                           placeholder="Ingrese Nombre" onkeypress="return validarLetras(event)"/>
                </div>

                <div class="form-group">
                    <label>Fecha Nacimiento</label><br>
                    <input type="date" name="txtFechaNacimiento" value="" required="" id="datepicker" class="form-control"
                           max="2000-12-31" />
                </div>
                
                <div class="form-group">
                    <label>Telefono de Contacto</label><br> 
                    <input type="number" name="txtTelefono" value="" required="" class="form-control"
                           placeholder="Ingrese N° Telefono"
                           min="111111111"/>
                </div>
                
                <div class="form-group">
                    <label>Región</label><br>
                    <select class="custom-select" name="cmbRegiones" id="id_cmbRegiones" >                         
                        <option value="arica">Región de Arica y Parinacota</option>
                        <option value="tarapaca">Región de Tarapaca</option>
                        <option value="antofagasta">Región de Antofagasta</option>
                        <option value="atacama">Región de Atacama</option>
                        <option value="coquimbo">Región de Coquimbo</option>
                        <option value="valparaiso">Región de Valparaiso</option>
                        <option value="ohiggins">Región del Libertador General Bdo. O'Higgins</option>
                        <option value="maule">Región del Maule</option>
                        <option value="biobio">Región de Biobio</option>
                        <option value="araucania">Región de La Araucania</option>
                        <option value="rios">Región de Los Rios</option>
                        <option value="lagos">Región de Los Lagos</option>
                        <option value="aisen">Región Aisén del Gral. Carlos Ibáñez del Campo</option>
                        <option value="magallanes">Región de Magallanes y de la Antártica Chilena</option>
                        <option value="metropolitana">Región Metropolitana de Santiago</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label>Comuna</label><br>
                    <select class="custom-select" name="cmbComunas" id="id_cmbComunas">
                    </select>
                </div>
                
                <div class="form-group">
                    <label>Tipo de Vivienda</label><br>
                    <select class="custom-select" name="cmbTipoVivienda" id="id_cmbTipoVivienda">
                        <option>Casa con Patio Grande</option>
                        <option>Casa con Patio Pequeño</option>
                        <option>Casa sin Patio</option>
                        <option>Departamento</option>
                    </select>
                </div>
                <br>
                <div class="form-group">
                    <input class="btn" type="submit" value="Enviar" name="btnEnviar" id="enviar"/>
                </div>
            </form>

        </div>

        <!-- Pie de página -->
        <div id="footer">
            <p>Desarollo Web y Mobile - Ariel Chácon, Nicolás Leporati</p>
        </div>

    </body>
</html>

app/templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>


<head>
    <title>{% block title %} Gamers {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">





</head>

<style>
    body {
        background-image: url("{% static 'img/fondo.png' %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: 100% 100%;
        background-attachment: fixed;
        color:cyan;
        
    }
</style>

<body>
    <div class="content">
        <header id="capa2">
            <div class="menu_bar">
                <a href="#" class="bt-menu"><span class="icon-menu"></span>Menu</a>
            </div>

            <nav>
                <ul>

                    <li><a href="http://localhost:8000/"><span class="icon-home"></span>Inicio</a></li>
                    <li><a href="http://localhost:8000/quienes"><span class="icon-rocket"></span>Nosotros</a></li>


                    <li><a href="https://twitter.com"><span class="icon-twitter-square"></span>Twitter</a></li>
                    <li><a href="https://facebook.com"><span class="icon-facebook-square"></span>Facebook</a></li>
                    <li><a href="https://web.whatsapp.com/"><span class="icon-whatsapp"></span>Whatsapp</a></li>
                    <li><a href="https://instagram.com"><span class="icon-instagram"></span>Instagram</a></li>
                    <li><a href="https://gmail.com"><span class="icon-envelop"></span>Correo</a></li>
                    <li><a href="http://localhost:8000/api"><span class="icon-file-text"></span>Api Rest
                        Cliente</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="http://localhost:8000/logout/"><span class="icon-clipboard"></span>Cerrar Sesión</a>
                    </li>
                    <li><a href="http://localhost:8000/listarProductos"><span class="icon-file-text"></span>Listar
                            Productos</a></li>

                    <li><a href="http://localhost:8000/listarClientes"><span class="icon-file-text"></span>Listar
                            Clientes</a></li>

                    <li><a href="http://localhost:8000/listarProductosFull"><span class="icon-file-text"></span>Editar
                            Producto</a></li>
                    <li><a href="http://localhost:8000/listarClientesFull"><span class="icon-file-text"></span>Editar
                            Cliente</a></li>

                    <li><a href="http://localhost:8000/ingresarProducto"><span class="icon-file-text"></span>Agregar
                            Producto</a></li>
                    <li><a href="http://localhost:8000/ingresarCliente"><span class="icon-file-text"></span>Agregar
                            Cliente</a></li>

                    

                    {% else %}
                    <li><a href="http://localhost:8000/inicio"><span class="icon-clipboard"></span>Iniciar Sesión</a>
                    </li>

                    {% endif %}
                </ul>
            </nav>
        </header>

        <!-- Carrusel -->


        {% block content %}
        {% endblock %}

        {% block footer %}

        {% endblock %}
    </div>

    <!-- Scripts -->

    <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
    <script src="{% static 'js/jquery-latest.js' %}"></script>
    <script src="{% static 'js/menu.js' %}"></script>
    <script src="{% static 'js/lightbox-plus-jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-latest.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrajs %}
    <!-- Pie de página -->


</body>

{% endblock %}
<div id="footer">
    <h6>Creado por JA JD NB</h6>
</div>

</html>

app/templates/app/baseAgregar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">


<head>
    <title>{% block title %}Gamers{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script> -->




</head>

<style>
    body {
        background-image: url("{% static 'img/fondo.png' %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: 100% 100%;
        background-attachment: fixed;
        
    }
</style>

<body>
    <div class="content">
        <header id="capa2">
            <div class="menu_bar">
                <a href="#" class="bt-menu"><span class="icon-menu"></span>Menu</a>
            </div>

            <nav>
                <ul>
                    <!-- <li><a href="http://localhost:8000/ingresarProducto"><span class="icon-newspaper"></span>Ingresar Producto</a></li> -->
                    <!-- <li><a href="http://localhost:8000/listarProductos"><span class="icon-file-text"></span>Listar Productos</a></li> -->
                    <li><a href="http://localhost:8000/"><span class="icon-home"></span>Inicio</a></li>

                </ul>
            </nav>
        </header>

        <!-- Carrusel -->


        {% block content %}
        {% endblock %}

        {% block footer %}
        <!-- Pie de página -->
        <div id="footer">
            <h6>Creado por JA JD NB</h6>
        </div>
        {% endblock %}
    </div>
</body>

</html>

app/templates/app/baseLogin.html
{% load staticfiles %}
<!DOCTYPE html>
<html >

        
<head>
    <title>Gamers{% block title %} Title {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script> -->



    
</head>

<style>
    body {
    background-image: url( "{% static 'img/fondo.png' %}");
    background-position: center;
    background-repeat: no-repeat;
    background-size: 100% 100%;
    background-attachment: fixed;
  }
</style>
 
<body >

   

    {% block content %}   
    {% endblock %}

    {% block footer %}
    <!-- Pie de página -->
    <div id="footer">
        
    </div>
    {% endblock %}    

app/templates/app/blairWitch.html
{% extends 'app/base.html' %}

{% block content %}
{% load staticfiles %}
<link  href="{% static 'css/estilos.css' %}" rel="stylesheet">
<!-- <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
<link  href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">
<!-- <link  href="{% static 'css/carrusel.css' %}" rel="stylesheet"> -->
<link  href="{% static 'css/menu.css' %}" rel="stylesheet">
<link  href="{% static 'css/galeria1.css' %}" rel="stylesheet">
<link  href="{% static 'css/lightbox.min.css' %}" rel="stylesheet">
<!-- <link  href="{% static 'css/menuFijo.css' %}" rel="stylesheet"> -->
<link  href="{% static 'css/rrss.min.css' %}" rel="stylesheet">

<body>
    

        
    <h1 id="video_1">Blair Witch</h1>




    <div>
        <iframe class="video1" width="500" height="315" src="https://www.youtube.com/embed/RpJinaWyAd0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


        <div class="contenedor">

            <div class="padre1">

                <div class="hijo1">
                    <h2 id="t1">Blair Witch PC-GAME</h2>
                    <p id="p1">Género: Aventura, Indie, Terror
                        Fecha de lanzamiento: 30 de Agosto de 2019
                        Fecha de Actualización: 04 de Septiembre de 2019
                        Tamaño: 12.8 Gigas
                        Formato: ISO
                        Idioma Voces: Ingles
                        Idioma Textos: Español, Ingles, Francés, Italiano, Portugués de Brasil, entre otros.</p>
                    <img id="img1" src="{% static 'img/imgBlairWitch/Blair-Witch-2019-PC-imagen-001.png' %}">
                </div>


                <div class="hijo2">
                    <h2 id="t2">Acerca de «Blair Witch (2019)» para PC</h2>
                    <p id="p2">Es el año 1996. Un niño ha desaparecido en el bosque de Black Hills, a las afueras de
                        Burkitsville, Maryland. Te unirás a la búsqueda como Ellis, un ex-agente de policía con un
                        pasado
                        turbio. Lo que empieza como una investigación policial normal, pronto se convertirá en una
                        pesadilla
                        sin
                        fin a medida que te enfrentes a tus miedos y a la bruja de Blair, una entidad misteriosa que
                        frecuenta
                        el bosque…</p>
                    <img id="img2" src="{% static 'img/imgBlairWitch/Blair-Witch-2019-PC-imagen-002.png' %}">
                </div>


                <div class="hijo3">
                    <h2 id="t3">Características llamativas del juego</h2>
                    <p id="p3">
                        Una historia sobre el descenso personal a la oscuridad: De las mentes creativas detrás del
                        aclamado
                        Layers of Fear llega este título en el que experimentarás un miedo que inundará tu mente a
                        través
                        una
                        historia original basada en la leyenda de la Bruja de Blair.
                        Encuentra el camino en el bosque embrujado: Acompañado solo por tu fiel perro Bullet, ábrete
                        camino
                        a
                        través de un bosque maldito que distorsiona el tiempo y el espacio.
                        Tu cordura contra su maldición: Enfréntate a la terrorífica a la bruja de Blair y a la decadente
                        cordura
                        de un hombre atormentado por su pasado.
                        ¿Como te enfrentaras a tus miedos?: A medida que te adentres en el bosque, tus reacciones al
                        peligro
                        y
                        tu comportamiento bajo presión te enseñarán cada vez más sobre ti mismo.
                    </p>
                    <img id="img3" src="{% static 'img/imgBlairWitch//Blair-Witch-2019-PC-imagen-003.png' %}">
                </div>


                <div class="hijo4">
                    <h2 id="t4">Requerimientos de Sistema</h2>
                    <p id="p4">
                        Mínimos:
                        Requiere un procesador y un sistema operativo de 64 bits
                        Sistema Operativo: Windows 7
                        Procesador: Intel Core i3-3220 (3.30 GHz) | AMD A8-7600 (3.1 GHz)
                        Memoria: 4 Gigas de RAM
                        Gráficos: GeForce GTX 750 Ti | AMD Radeon R7 265
                        DirectX: Versión 11
                        Almacenamiento: 16 Gigas de espacio disponible
                        Tarjeta de sonido: DirectX 11.0 compatible

                        Recomendados:
                        Sistema Operativo: Windows 10 de 64 bits
                        Procesador: Intel Core i5-6500 (3.2 GHz) | AMD Ryzen 5 1600
                        Memoria: 8 Gigas de RAM
                        Gráficos: GeForce GTX 1070 | AMD Radeon RX 590
                        DirectX: Versión 11
                        Almacenamiento: 16 Gigas de espacio disponible
                    </p>
                    <img id="img4" src="{% static 'img/imgBlairWitch/Blair-Witch-2019-PC-imagen-004.png' %}">
                </div>

            </div>

        </div>
    </div>

    <p>
        <a href="#" id="volver">Volver al inicio de la página</a>
    </p>
    </body>
{% endblock content %}

app/templates/app/cliente_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>primera pagina DJango</title>
</head>
<body>
    <h1>LLegamos a la plantilla</h1>
</body>
</html>

app/templates/app/editarCliente.html
{% extends 'app/baseAgregar.html' %}

{% block content %}
{% load staticfiles %}
<link  href="{% static 'css/form.css' %}" rel="stylesheet">

<link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link  href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">

<link  href="{% static 'css/menu.css' %}" rel="stylesheet">


<body>
    <h1 class="f">Editar Cliente</h1>
   <form class="g" method="POST">
        {{ form }}
        {% csrf_token %}
        <button  type="submit" >Editar</button><button><a href="http://localhost:8000/listarClientesFull">Volver</a></button>
   </form>
</body>
{% endblock content %}

app/templates/app/editarProducto.html
{% extends 'app/baseAgregar.html' %}

{% block content %}
{% load staticfiles %}
<link  href="{% static 'css/form.css' %}" rel="stylesheet">
<!-- <link  href="{% static 'css/estilos.css' %}" rel="stylesheet"> -->
<link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link  href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">
<!-- <link  href="{% static 'css/carrusel.css' %}" rel="stylesheet"> -->
<link  href="{% static 'css/menu.css' %}" rel="stylesheet">
<!-- <link  href="{% static 'css/galeria1.css' %}" rel="stylesheet">
<link  href="{% static 'css/lightbox.min.css' %}" rel="stylesheet"> -->
<!-- <link  href="{% static 'css/menuFijo.css' %}" rel="stylesheet"> -->
<!-- <link  href="{% static 'css/rrss.min.css' %}" rel="stylesheet"> -->

<body>
    <h1 class="f">Editar Producto</h1>
   <form class="g" method="POST">
        {{ form }}
        {% csrf_token %}
        <button  type="submit" >Editar</button><button><a href="http://localhost:8000/listarProductosFull">Volver</a></button>
   </form>
</body>
{% endblock content %}

app/templates/app/ingresarProducto.html
{% extends 'app/baseAgregar.html' %}

{% block content %}
{% load staticfiles %}


<link href="{% static 'css/form.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/icomoon/style.css' %}" rel="stylesheet">
<link href="{% static 'css/menu.css' %}" rel="stylesheet">
<h3 class="user">Bienvenido </h3>
<h3 class="user">{{user.username}}</h3>
<body>
    <h1 class="f">Ingresar Producto</h1>
       
    <div id="registro" class="container">
        <form  role="form" enctype="multipart/form-data" action="" method="POST" id="upload-image-form">

            {% csrf_token %}
            <!-- {{ form}} -->

            <div class="form-group">
                <label for="id_nombre">Nombre:</label><input type="text" name="nombre" maxlength="50" required=""
                    id="id_nombre" class="form-control" placeholder="Ingrese Nombre Producto">
            </div>
            <div class="form-group">
                <label for="id_descripcion">Descripción:</label><input type="text" name="descripcion" maxlength="50"
                    required="" id="id_descripcion" class="form-control" placeholder="Ingrese Descripción">
            </div>
            <div class="form-group">
                <label for="id_clasificasion">Clasificación:</label><input type="text" name="clasificacion"
                    maxlength="50" required="" id="id_clasificasion" class="form-control" placeholder="Ingrese Nombre">
            </div>
            <div class="form-group">
                <label for="id_precio">Precio:</label><input type="number" name="precio" maxlength="50" required=""
                    id="id_precio" class="form-control" placeholder="Ingrese Precio">
            </div>

            
            <button type="submit">GRABAR</button>
        </form>
    </div>
</body>
{% endblock content %}